name: Run Python tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
    - name: Install apt dependencies
      run: sudo apt install -y yosys
    - name: Run tests
      run: uv run just tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
