# See PyRTL's release documentation in docs/release/README.md
#
# This file configures GitHub actions for building distribution archives and
# uploading them to PyPI.
#
# This configuration is based on the "Publishing package distribution releases
# using GitHub Actions" tutorial at
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: Build and publish release

on: push

jobs:
  # Verify that distribution archives can be built on every push.
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        enable-cache: true
    - name: Build distribution archives
      run: uv build
    - name: Upload distribution archives
      uses: actions/upload-artifact@v7
      with:
        name: python-distribution-archives
        path: dist/
        compression-level: 0

  # Publish distribution archive to TestPyPI on tag pushes.
  publish-testpypi:
    # Only publish to TestPyPI on tag pushes.
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyrtl
    permissions:
      # Required for trusted publishing.
      id-token: write

    steps:
    - name: Download distribution archives
      uses: actions/download-artifact@v7
      with:
        name: python-distribution-archives
        path: dist/
    - name: Publish distribution archives
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  # Publish distribution archive to PyPI on tag pushes. The 'pypi' environment
  # requires manual approval on GitHub, so this job won't start automatically.
  publish-pypi:
    # Only publish to PyPI on tag pushes.
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyrtl
    permissions:
      # Required for trusted publishing.
      id-token: write

    steps:
    - name: Download distribution archives
      uses: actions/download-artifact@v8
      with:
        name: python-distribution-archives
        path: dist/
    - name: Publish distribution archives
      uses: pypa/gh-action-pypi-publish@release/v1
